language: node_js
node_js:
  - "stable"
env:
  - "CI=false"
cache:
  directories:
  - node_modules
script:
  - cd ./node/client
  - npm install
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
