version: '3'
services:
  ####################
  # NODE
  ####################
  node:
    container_name: StoreApp
    build         : ./node
  ####################
  # MONGO
  ####################
  # mongodb:
  #   image         : mongo:latest
  #   container_name: Database_StoreApp
  #   build         : ./mongo
  #   ports:
  #     - "27017:27017"
  #####################
  # NGINX
  #####################
  nginx:
    container_name: Nginx_StoreApp
    build         : ./nginx
    links         :
      - node
    ports:
      - "80:80"
      - "443:443"
