version: '3'
services:
  ####################
  # React/Client
  ####################
  client:
    image         : node:carbon
    container_name: Client
    build         : ./react
  ####################
  # Server
  ####################
  server:
    image         : node:carbon
    container_name: Server
    build         : ./server
  #####################
  # NGINX
  #####################
  nginx:
    image         : nginx:stable
    container_name: Nginx
    build         : ./nginx
    links         :
      - client
    ports:
      - "80:80"
      - "443:443"
  ####################
  # MONGO
  ####################
  mongodb:
    image         : mongo:latest
    container_name: Database
    build         : ./mongo
    ports:
      - "27017:27017"
    links         :
      - server