version: '3'
services:
  ####################
  # React
  ####################
  client:
    image         : node:carbon
    container_name: Client_StoreApp
    build         : ./client
  ####################
  # NODE
  ####################
  server:
    image         : node:carbon
    container_name: API_StoreApp
    build         : ./server
    links         :
      - mongodb
  ####################
  # MONGO
  ####################
  mongodb:
    image         : mongo:latest
    container_name: Database_StoreApp
    build         : ./mongo
    ports:
      - "27017:27017"
  #####################
  # NGINX
  #####################
  nginx:
    image         : nginx:stable
    container_name: Nginx_StoreApp
    links         :
      - client
      - server
    ports:
      - "80:80"
      - "443:443"