version: '2.1'

services:
  server:
    build: ./server
    ports:
     - "1337:1337"
    environment:
      - "NODE_ENV=DEV"
      - "USE_DOCKER=yes"
    depends_on:
      - mysql
    links: 
        - mysql
        # - redis
  mysql:
    image: mysql:latest
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=storeapp"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=homestead"
    ports:
      - "3306:3306"
  # redis:
  #   image: redis:4.0-alpine
  #   command: redis-server --appendonly yes
  #   ports:
  #     - "6379:6379"
volumes:
  mysqldata: