version: '2'

services:
  server:
    build: ./server
    ports:
     - "1337:1337"
    environment:
      NODE_ENV: DEV
  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: homestead
        MYSQL_USER: root
        MYSQL_PASSWORD: secret
  redis:
    image: redis:4.0-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"